import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

const Card = () => {
  interface SlipType {
    id: number;
    advice: string;
  }
  const getAdvice = async () => {
    // await fetch("https://api.adviceslip.com/advice",{
    //   method:"GET",
    //   headers: {
    //     'Accept': 'application/json',
    // },
    // })
    // .then((response)=>{
    //   console.log(response)
    // })
    // .then(data => console.log(data))
    // .catch((error)=>console.error(error))
    await axios
      .get("https://api.adviceslip.com/advice")
      .then((res) => {
        if (res.data) {
          setAdvice(res.data.slip);
        }
        console.log(res);
      })
      .catch((err) => console.error(err));
  };
  const [advice, setAdvice] = useState<SlipType | null>(null);
  return (
    <div className="min-w-[250px] max-w-[600px] min-h-[300px] text-center bg-dark-grayish rounded-md shadow-2xl p-6 box-border">
      <div className="w-full h-full">
        <p className="text-neon-green uppercase tracking-[5px] text-[10px]">
          {" "}
          advice #{advice?.id}{" "}
        </p>
        <p className="text-white my-3 min-h-[200px]">"{advice?.advice}"</p>
      </div>
      <div className="relative">
        <div className="w-full h-[10px] relative my-4">
          <Image fill src={"/images/pattern-divider-desktop.svg"} alt="" />
        </div>
      </div>
      <div
        onClick={getAdvice}
        className="bg-neon-green rounded-full h-8 w-8  bottom-[-25px] absolute  left-1/2 -translate-x-1/2 cursor-pointer hover:shadow-[0px_0px_30px_5px] hover:shadow-neon-green"
      >
        <div className="w-1/2 h-1/2 full-center ">
          <Image fill src={"/images/icon-dice.svg"} alt="" />
        </div>
      </div>
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Advice Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@800&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <div className="full-center">
          <Card />
        </div>
      </main>
    </>
  );
}
